### PR TITLE
Add quality of life features

### PR DESCRIPTION
**Pull request by Sup2point0**
### Changes

- stylise the submit button
- add `ctrl+enter` keyboard shortcut for automagically clicking the submit button
- may have improved the UI/X

### Tests

- [x] HTML
- [x] CSS
- [ ] JS
- [ ] Python

### CODE REVIEW

**Comment by iTechnicals** [comment]
is this a troll, why is everything comic sans (also ctrl+enter for submit is already implemented)

**Comment by macaquedev** [comment]
oh damn oliver appears in real time

**Comment by macaquedev** [comment]
oh damn itechnicals appears in real time (also yeah, I've done ctrl-enter already)

**Comment by Sup2point0** [comment]
oh damn, my bad

**Comment by iTechnicals** [comment]
image
😭

**Comment by iTechnicals** [comment]
i do appreciate the contribution, just not gonna sift through to find which features are good and which ones are *ahem* hot trash. maybe there's potential here for an april fools contest.

**Comment by macaquedev** [comment]
april fools PyDash YES PLEASE!!!

**Comment by Sup2point0** [comment]
that will take quite the while lmao

**Pull request closed without merging**
